# Generated by Django 5.2.8 on 2025-11-30 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.CharField(choices=[('manual', 'Manual'), ('pa11y', 'pa11y')], default='manual', max_length=20)),
                ('issues_found', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('last_audit', models.DateTimeField(blank=True, null=True)),
                ('issues', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WCAGIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('wcag', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('selector', models.TextField(blank=True)),
                ('context', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('impact', models.CharField(blank=True, max_length=20)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wcag_issues', to='audit.auditrecord')),
            ],
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='audit.webpage'),
        ),
    ]
